#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path:       /login_check

gesdinet_jwt_refresh_token:
    path:       /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh