name: Continuous Integration

on: [pull_request]

jobs:
  quality:
    name: Quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHP Code Sniffer
        if: ${{ always() }}
        run: vendor/bin/phpcs --standard=PSR2 src

      - name: PHP Mess Detector
        if: ${{ always() }}
        run: vendor/bin/phpmd src/ text codesize,controversial,phpmd.xml

      - name: PHP Stan
        if: ${{ always() }}
        run: vendor/bin/phpstan analyse -c phpstan.neon

      - name: PHP Unit tests
        if: ${{ always() }}
        run: bin/phpunit
